name: Test and Build

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '["20.x"]'
        type: string
      upload-coverage:
        description: 'Whether to upload coverage to Codecov'
        required: false
        default: true
        type: boolean
      upload-artifacts:
        description: 'Whether to upload build artifacts'
        required: false
        default: false
        type: boolean
      artifact-retention-days:
        description: 'How long to retain artifacts (days)'
        required: false
        default: 7
        type: number
    outputs:
      build-successful:
        description: 'Whether the build was successful'
        value: ${{ jobs.test.outputs.build-successful }}

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ${{ fromJSON(inputs.node-version) }}
    
    outputs:
      build-successful: ${{ steps.build.outcome == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Build plugin
        id: build
        run: npm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: inputs.upload-coverage && matrix.node-version == '20.x'
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: inputs.upload-artifacts && matrix.node-version == '20.x'
        with:
          name: obsidian-plugin-build
          path: |
            main.js
            manifest.json
            styles.css
          retention-days: ${{ inputs.artifact-retention-days }}
